### ISSUE TITLE
The /docs/ endpoint does not work.

### ISSUE THREAD

**Issue by SirWumpus** [xtrinch/fcm-django-web-demo#19]
Trying to connect to `https://localhost:8000/docs/` fails with the following console error stack:

```
Internal Server Error: /docs/
Traceback (most recent call last):
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/schemas/views.py", line 48, in handle_exception
    return super().handle_exception(exc)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/schemas/views.py", line 37, in get
    schema = self.schema_generator.get_schema(request, self.public)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/schemas/coreapi.py", line 156, in get_schema
    links = self.get_links(None if public else request)
  File "/usr/home/anhoxa/git/fcm-django-web-demo/venv/lib/python3.7/site-packages/rest_framework/schemas/coreapi.py", line 143, in get_links
    link = view.schema.get_link(path, method, base_url=self.url)
AttributeError: 'AutoSchema' object has no attribute 'get_link'
[07/May/2021 12:50:42] "GET /docs/ HTTP/1.1" 500 100622
```

**Comment by xtrinch** [comment]
Resolved in latest master
